### PR TITLE
Check exit status for jniCompile and javah tasks

### PR DESCRIPTION
**Pull request by carymrobbins**
This ensures that if these tasks fail, you get an `[error]` status in SBT.

### CODE REVIEW

**Comment by joprice** [comment]
Thanks for the fix. I don't have this repo set up with automated test, so if you don't mind, I'm going to set up travis and add a scripted test before I merge this.

**Comment by carymrobbins** [comment]
Sounds like a good idea, I'm just using my locally published one for now.

**Comment by joprice** [comment]
I have everything setup now. Looks like you need to rebase now.

**Comment by carymrobbins** [comment]
@joprice - Rebased and all checks pass.

**Comment by joprice** [comment]
Thanks!

**Pull request merged**
